// src/components/templates.js
export const templates = {
    mikrotik: {
      NOME: '',
      IP_ADDRESS: '',
      INTERFACE: '',
      GATEWAY: '',
      TIMEZONE: '',
      NOME_INTERFACE: '',
      CONTATO: '',
      LOCALIZACAO: '',
      DNS_SERVER1: '',
      DNS_SERVER2: '',
      BRIDGE_NAME: '',
      INTERFACE_BRIDGE: '',
      BLOCKED_IP: '',
    },
    cisco: {
      DEVICE_NAME: '',
      IP_ADDRESS: '',
      SUBNET_MASK: '',
      DEFAULT_GATEWAY: '',
      DNS_SERVER1: '',
      DNS_SERVER2: '',
      INTERFACE_NAME: '',
      VLAN: '',
      ENABLE_SECRET: '',
      HOSTNAME: '',
      DOMAIN_NAME: '',
      NAT: '',
      SSH_VERSION: '',
    },
    ubiquiti: {
      HOSTNAME: '',
      IP_ADDRESS: '',
      NETMASK: '',
      GATEWAY: '',
      DNS_SERVER: '',
      NTP_SERVER: '',
      ADMIN_PASSWORD: '',
      VLAN_ID: '',
      VLAN_NAME: '',
      WiFi_SSID: '',
      WiFi_PASSWORD: '',
    },
    juniper: {
      HOSTNAME: '',
      IP_ADDRESS: '',
      NETMASK: '',
      GATEWAY: '',
      DNS_SERVER: '',
      NTP_SERVER: '',
      INTERFACE_NAME: '',
      VLAN_ID: '',
      DESCRIPTION: '',
      ROOT_PASSWORD: '',
    },
    arista: {
      HOSTNAME: '',
      IP_ADDRESS: '',
      SUBNET_MASK: '',
      DEFAULT_GATEWAY: '',
      DNS_SERVER1: '',
      DNS_SERVER2: '',
      VLAN: '',
      INTERFACE_NAME: '',
      MTU: '',
      ENABLE_PASSWORD: '',
    },
  };
  